package com.klim.voicedatasetcollector.recording

import android.content.Context

object DatasetStats {
    data class Snapshot(
        val wavFiles: Int,
        val audioDurationMs: Long,
        val wavBytes: Long
    )

    fun calculate(context: Context): Snapshot {
        val root = RecordingPaths.recordingsRoot(context)
        var count = 0
        var durationMs = 0L
        var bytes = 0L

        root.walkTopDown()
            .filter { it.isFile && it.extension.equals("wav", ignoreCase = true) && it.parentFile?.name != "clean" }
            .forEach { file ->
                count++
                val size = file.length()
                bytes += size + java.io.File(file.parentFile, "clean/${file.name}").let { if (it.exists()) it.length() else 0L }

                // WAV generated by this app: PCM16, mono, 16 kHz, 44-byte header.
                val pcmBytes = (size - 44L).coerceAtLeast(0L)
                durationMs += pcmBytes * 1000L / (AudioConfig.SAMPLE_RATE * 2L)
            }

        return Snapshot(count, durationMs, bytes)
    }
}
